"""
NetGuard license minter — signs a license payload with the private key
generated by tools/license_keygen.py.

Usage (single-PC legacy):
    python tools/license_mint.py <tier> [--expires YYYY-MM-DD] [--machine <id>]

Usage (multi-PC, recommended):
    python tools/license_mint.py <tier> --plan {starter|pro} --seats N \\
        --customer-email user@example.com --expires-days 365

Examples:
    # Legacy single-PC, perpetual:
    python tools/license_mint.py pro

    # 5-seat Pro plan, 1-year, output a .lic file:
    python tools/license_mint.py pro --plan pro --seats 5 \\
        --customer-email simon@example.com --expires-days 365 \\
        --out simon.lic

Outputs:
    NGPRO-<base64url-payload>-<base64url-signature>
"""
import argparse
import base64
import json
import sys
import uuid
from datetime import datetime, timedelta, timezone
from pathlib import Path

try:
    from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey
except ImportError:
    print("ERROR: install cryptography first  ->  pip install cryptography")
    sys.exit(1)

PRIV_PATH = Path(__file__).resolve().parent / "keys" / "license_ed25519.priv"

PLAN_SEAT_CAPS = {"starter": 1, "pro": 5}


def _b64url(b: bytes) -> str:
    return base64.urlsafe_b64encode(b).rstrip(b"=").decode("ascii")


def main() -> int:
    parser = argparse.ArgumentParser(description="Mint a NetGuard license key")
    parser.add_argument("tier", choices=["pro", "enterprise"])
    parser.add_argument("--expires", default=None,
                        help="ISO date (YYYY-MM-DD) — empty = perpetual (legacy)")
    parser.add_argument("--expires-days", type=int, default=None,
                        help="Issue with expires_at = now + N days "
                             "(takes precedence over --expires)")
    parser.add_argument("--machine", default=None,
                        help="Bind license to this machine_id (sha256 prefix). "
                             "Empty = portable. Multi-PC licenses leave this empty.")
    parser.add_argument("--customer", default=None,
                        help="Optional customer label embedded in the payload")
    parser.add_argument("--customer-email", default=None,
                        help="Customer email (required for multi-PC licenses)")
    parser.add_argument("--plan", choices=["starter", "pro"], default=None,
                        help="Pricing plan; sets the multi-PC seat cap")
    parser.add_argument("--seats", type=int, default=1,
                        help="Number of seats (1..5). Hard-capped by --plan: "
                             "starter=1, pro=5. Default 1.")
    parser.add_argument("--license-id", default=None,
                        help="UUID for this license. Auto-generated if omitted.")
    parser.add_argument("--out", default=None,
                        help="Write a single-line .lic file at this path "
                             "(in addition to printing to stdout)")
    args = parser.parse_args()

    if not PRIV_PATH.exists():
        print(f"ERROR: {PRIV_PATH} not found. Run tools/license_keygen.py first.")
        return 1

    priv = Ed25519PrivateKey.from_private_bytes(PRIV_PATH.read_bytes())

    # Resolve seats vs plan caps
    plan = args.plan
    seats = max(1, int(args.seats or 1))
    if plan in PLAN_SEAT_CAPS:
        cap = PLAN_SEAT_CAPS[plan]
        if seats > cap:
            print(f"WARN: --seats {seats} > {plan} cap ({cap}); clamping to {cap}",
                  file=sys.stderr)
            seats = cap
        if plan == "starter":
            seats = 1

    # Resolve expires vs expires-days
    expires_iso = args.expires
    if args.expires_days is not None:
        exp_dt = datetime.now(timezone.utc) + timedelta(days=int(args.expires_days))
        expires_iso = exp_dt.isoformat().replace("+00:00", "Z")

    license_id = args.license_id or str(uuid.uuid4())

    payload = {
        "tier": args.tier,
        "plan": plan,
        "max_seats": seats,
        "license_id": license_id,
        "customer_email": args.customer_email,
        "customer": args.customer,
        "machine_id": args.machine,
        "expires": expires_iso,           # legacy field name (still honoured)
        "expires_at": expires_iso,        # new canonical field
        "issued_at": datetime.now(timezone.utc).isoformat().replace("+00:00", "Z"),
    }
    # Drop None values to keep the payload tight & signed bytes minimal
    payload = {k: v for k, v in payload.items() if v is not None}

    payload_bytes = json.dumps(payload, separators=(",", ":"), sort_keys=True).encode("utf-8")
    sig = priv.sign(payload_bytes)

    key = f"NGPRO-{_b64url(payload_bytes)}-{_b64url(sig)}"
    print(key)
    print()
    print(f"# tier={args.tier} plan={plan or 'legacy'} seats={seats} "
          f"expires={expires_iso or 'never'} license_id={license_id}")

    if args.out:
        out_path = Path(args.out)
        out_path.write_text(key + "\n", encoding="utf-8")
        print(f"# written to {out_path}", file=sys.stderr)

    return 0


if __name__ == "__main__":
    sys.exit(main())
