"""
NetGuard license minter — signs a license payload with the private key
generated by tools/license_keygen.py.

Usage:
    python tools/license_mint.py <tier> [--expires YYYY-MM-DD] [--machine <id>]

Examples:
    python tools/license_mint.py pro --expires 2027-01-01
    python tools/license_mint.py enterprise
    python tools/license_mint.py pro --machine abc123def456

Outputs a license key of the form:
    NGPRO-<base64url-payload>-<base64url-signature>
"""
import argparse
import base64
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

try:
    from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey
except ImportError:
    print("ERROR: install cryptography first  ->  pip install cryptography")
    sys.exit(1)

PRIV_PATH = Path(__file__).resolve().parent / "keys" / "license_ed25519.priv"


def _b64url(b: bytes) -> str:
    return base64.urlsafe_b64encode(b).rstrip(b"=").decode("ascii")


def main() -> int:
    parser = argparse.ArgumentParser(description="Mint a NetGuard license key")
    parser.add_argument("tier", choices=["pro", "enterprise"])
    parser.add_argument("--expires", default=None,
                        help="ISO date (YYYY-MM-DD) — empty = perpetual")
    parser.add_argument("--machine", default=None,
                        help="Bind license to this machine_id (sha256 prefix). Empty = portable.")
    parser.add_argument("--customer", default=None,
                        help="Optional customer label embedded in the payload")
    args = parser.parse_args()

    if not PRIV_PATH.exists():
        print(f"ERROR: {PRIV_PATH} not found. Run tools/license_keygen.py first.")
        return 1

    priv = Ed25519PrivateKey.from_private_bytes(PRIV_PATH.read_bytes())

    payload = {
        "tier": args.tier,
        "expires": args.expires,
        "machine_id": args.machine,
        "customer": args.customer,
        "issued_at": datetime.now(timezone.utc).isoformat().replace("+00:00", "Z"),
    }
    payload_bytes = json.dumps(payload, separators=(",", ":"), sort_keys=True).encode("utf-8")
    sig = priv.sign(payload_bytes)

    key = f"NGPRO-{_b64url(payload_bytes)}-{_b64url(sig)}"
    print(key)
    print()
    print(f"# tier={args.tier} expires={args.expires or 'never'} machine={args.machine or 'any'}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
